In [1]:
import pandas as pd
import numpy as np
import os
import joblib
from pathlib import Path
from functools import reduce

# Importation et jointure des 3  bases de données

In [2]:
path = Path("DATA_PRETRAITEMENT")

In [3]:
df_membre, df_reward, df_transaction = [pd.read_csv(path/i) for i in os.listdir(path) if (Path(i).suffix == ".csv") & (i != 'df_segmentation.csv')]

In [4]:
df_to_be_merged = [df_membre, df_transaction, df_reward]

In [5]:
#COPIE_MEMBERS_ID
df_segmentation_copy_sociodem = df_membre[['MEMBER_ID','AGE', 'GENDER', 'PROV']]
#df_segmentation_copy_sociodem

In [6]:
# On remplace les NaN par 0 car cela signie que le membre n'a pas fait de réclamation
df_segmentation = reduce(lambda left, right : pd.merge(left, right, on='MEMBER_ID', how="left"), df_to_be_merged).fillna(0)

In [7]:
df_segmentation

,MEMBER_ID,AGE,GENDER,TENURE_MONTHS,PROV,CASH_BACK_POINTS_BALANCE,REWARD_POINTS_BALANCE,BASE_POINTS_EARNED,BONUS_POINTS_EARNED,REWARD_POINTS_EARNED,CASH_BACK_POINTS_EARNED,RECENCY,NUMBER_CATEGORIES_PURCHASED_FROM,COVID_TRANSACTIONS_PCT_CHANGE,REDEMPTIONS,NUMBER_ITEMS_REDEEMED,POINTS_REDEEMED_PCT_CHANGE_2021
0,859615,80.0,M,362,ON,14,636,224.0,230.0,0.0,454.0,0.0,4.0,0.081967,5.0,5.0,0.000000
1,12684534,60.0,F,256,MB,0,419,121.0,32.0,153.0,0.0,0.0,5.0,-0.969697,1.0,1.0,0.000000
2,14130778,47.0,F,236,QC,116,195,485.0,377.0,0.0,862.0,0.0,4.0,-0.244681,3.0,10.0,-0.333333
3,18899440,39.0,0,185,QC,0,7,11.0,0.0,11.0,0.0,750.0,2.0,0.000000,0.0,0.0,0.000000
4,1011315776,0.0,0,47,0,0,0,1.0,0.0,1.0,0.0,1050.0,1.0,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202980,1982154,67.0,F,288,ON,0,1002,88.0,56.0,144.0,0.0,0.0,4.0,-0.148148,0.0,0.0,0.000000
1202981,5806235,62.0,F,351,QC,186,331,164.0,74.0,0.0,238.0,0.0,4.0,-0.744186,1.0,1.0,0.000000
1202982,17171682,62.0,0,209,ON,0,1828,128.0,25.0,153.0,0.0,0.0,3.0,1.315789,0.0,0.0,0.000000
1202983,18475293,33.0,0,184,ON,14,932,2082.0,126.0,464.0,1744.0,0.0,6.0,-0.236842,6.0,17.0,-0.666667
1202984,1016118761,23.0,M,43,ON,0,185,75.0,80.0,155.0,0.0,0.0,4.0,1.380952,0.0,0.0,0.000000

In [8]:
##probleme les nan des colonnes socio ont ete modifies par zero effacer colonnes sociodemographiques
df_segmentation.drop(['AGE', 'GENDER', 'PROV'], axis=1, inplace=True)
df_segmentation

,MEMBER_ID,TENURE_MONTHS,CASH_BACK_POINTS_BALANCE,REWARD_POINTS_BALANCE,BASE_POINTS_EARNED,BONUS_POINTS_EARNED,REWARD_POINTS_EARNED,CASH_BACK_POINTS_EARNED,RECENCY,NUMBER_CATEGORIES_PURCHASED_FROM,COVID_TRANSACTIONS_PCT_CHANGE,REDEMPTIONS,NUMBER_ITEMS_REDEEMED,POINTS_REDEEMED_PCT_CHANGE_2021
0,859615,362,14,636,224.0,230.0,0.0,454.0,0.0,4.0,0.081967,5.0,5.0,0.000000
1,12684534,256,0,419,121.0,32.0,153.0,0.0,0.0,5.0,-0.969697,1.0,1.0,0.000000
2,14130778,236,116,195,485.0,377.0,0.0,862.0,0.0,4.0,-0.244681,3.0,10.0,-0.333333
3,18899440,185,0,7,11.0,0.0,11.0,0.0,750.0,2.0,0.000000,0.0,0.0,0.000000
4,1011315776,47,0,0,1.0,0.0,1.0,0.0,1050.0,1.0,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202980,1982154,288,0,1002,88.0,56.0,144.0,0.0,0.0,4.0,-0.148148,0.0,0.0,0.000000
1202981,5806235,351,186,331,164.0,74.0,0.0,238.0,0.0,4.0,-0.744186,1.0,1.0,0.000000
1202982,17171682,209,0,1828,128.0,25.0,153.0,0.0,0.0,3.0,1.315789,0.0,0.0,0.000000
1202983,18475293,184,14,932,2082.0,126.0,464.0,1744.0,0.0,6.0,-0.236842,6.0,17.0,-0.666667
1202984,1016118761,43,0,185,75.0,80.0,155.0,0.0,0.0,4.0,1.380952,0.0,0.0,0.000000

In [9]:
#ajouter les variables socio a nouveau 
df_segmentation = pd.merge(df_segmentation, df_segmentation_copy_sociodem, on = "MEMBER_ID", how = "inner")
df_segmentation

,MEMBER_ID,TENURE_MONTHS,CASH_BACK_POINTS_BALANCE,REWARD_POINTS_BALANCE,BASE_POINTS_EARNED,BONUS_POINTS_EARNED,REWARD_POINTS_EARNED,CASH_BACK_POINTS_EARNED,RECENCY,NUMBER_CATEGORIES_PURCHASED_FROM,COVID_TRANSACTIONS_PCT_CHANGE,REDEMPTIONS,NUMBER_ITEMS_REDEEMED,POINTS_REDEEMED_PCT_CHANGE_2021,AGE,GENDER,PROV
0,859615,362,14,636,224.0,230.0,0.0,454.0,0.0,4.0,0.081967,5.0,5.0,0.000000,80.0,M,ON
1,12684534,256,0,419,121.0,32.0,153.0,0.0,0.0,5.0,-0.969697,1.0,1.0,0.000000,60.0,F,MB
2,14130778,236,116,195,485.0,377.0,0.0,862.0,0.0,4.0,-0.244681,3.0,10.0,-0.333333,47.0,F,QC
3,18899440,185,0,7,11.0,0.0,11.0,0.0,750.0,2.0,0.000000,0.0,0.0,0.000000,39.0,NaN,QC
4,1011315776,47,0,0,1.0,0.0,1.0,0.0,1050.0,1.0,0.000000,0.0,0.0,0.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202980,1982154,288,0,1002,88.0,56.0,144.0,0.0,0.0,4.0,-0.148148,0.0,0.0,0.000000,67.0,F,ON
1202981,5806235,351,186,331,164.0,74.0,0.0,238.0,0.0,4.0,-0.744186,1.0,1.0,0.000000,62.0,F,QC
1202982,17171682,209,0,1828,128.0,25.0,153.0,0.0,0.0,3.0,1.315789,0.0,0.0,0.000000,62.0,NaN,ON
1202983,18475293,184,14,932,2082.0,126.0,464.0,1744.0,0.0,6.0,-0.236842,6.0,17.0,-0.666667,33.0,NaN,ON
1202984,1016118761,43,0,185,75.0,80.0,155.0,0.0,0.0,4.0,1.380952,0.0,0.0,0.000000,23.0,M,ON

In [10]:
df_segmentation.shape

(1202985, 17)

# Renommer variables

In [11]:
df_segmentation.rename(columns={'RECENCY':'NB_J_DEPUIS_DERNIERE_TRANSACTION', 'POINTS_REDEEMED_PCT_CHANGE_2021':'PTS_RDMED_PCT_CHANGE_2020_2021','NUMBER_CATEGORIES_PURCHASED_FROM': 'NB_CATG_PURCHASED_FROM'}, inplace=True)

In [12]:
df_segmentation.columns = [i.upper() for i in df_segmentation.columns]

In [13]:
df_segmentation

,MEMBER_ID,TENURE_MONTHS,CASH_BACK_POINTS_BALANCE,REWARD_POINTS_BALANCE,BASE_POINTS_EARNED,BONUS_POINTS_EARNED,REWARD_POINTS_EARNED,CASH_BACK_POINTS_EARNED,NB_J_DEPUIS_DERNIERE_TRANSACTION,NB_CATG_PURCHASED_FROM,COVID_TRANSACTIONS_PCT_CHANGE,REDEMPTIONS,NUMBER_ITEMS_REDEEMED,PTS_RDMED_PCT_CHANGE_2020_2021,AGE,GENDER,PROV
0,859615,362,14,636,224.0,230.0,0.0,454.0,0.0,4.0,0.081967,5.0,5.0,0.000000,80.0,M,ON
1,12684534,256,0,419,121.0,32.0,153.0,0.0,0.0,5.0,-0.969697,1.0,1.0,0.000000,60.0,F,MB
2,14130778,236,116,195,485.0,377.0,0.0,862.0,0.0,4.0,-0.244681,3.0,10.0,-0.333333,47.0,F,QC
3,18899440,185,0,7,11.0,0.0,11.0,0.0,750.0,2.0,0.000000,0.0,0.0,0.000000,39.0,NaN,QC
4,1011315776,47,0,0,1.0,0.0,1.0,0.0,1050.0,1.0,0.000000,0.0,0.0,0.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202980,1982154,288,0,1002,88.0,56.0,144.0,0.0,0.0,4.0,-0.148148,0.0,0.0,0.000000,67.0,F,ON
1202981,5806235,351,186,331,164.0,74.0,0.0,238.0,0.0,4.0,-0.744186,1.0,1.0,0.000000,62.0,F,QC
1202982,17171682,209,0,1828,128.0,25.0,153.0,0.0,0.0,3.0,1.315789,0.0,0.0,0.000000,62.0,NaN,ON
1202983,18475293,184,14,932,2082.0,126.0,464.0,1744.0,0.0,6.0,-0.236842,6.0,17.0,-0.666667,33.0,NaN,ON
1202984,1016118761,43,0,185,75.0,80.0,155.0,0.0,0.0,4.0,1.380952,0.0,0.0,0.000000,23.0,M,ON

In [14]:
df_segmentation.shape

(1202985, 17)

In [15]:
# Vérifier si toutes les colonnes sont numériques
#assert len(df_segmentation.select_dtypes(include=np.number).columns) == df_segmentation.shape[1]

In [16]:
output_to_csv = True

In [17]:
if output_to_csv:
    df_segmentation.to_csv('DATA_PRETRAITEMENT/df_segmentation.csv', index=False)